### ISSUE TITLE
Investigate Import of Track Data from Audio Recordings

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2964]
### Description
Recordings are often digitized in workflows that do not include track-level metadata of the kind delivered by services such as Gracenote and CDDB. In the past these have mostly been queried by having physical media in a drive that can be read in such a way that is uniquely identifiable.

### Questions
- Can identifying information in an Avalon record be used to query a third party service, the response from which could be turned into Avalon structure within XML?
- Could there be a way to manually identify a file that could be hooked into a third party service?

**Comment by joncameron** [comment]
Questioning Authority has had third party services added—this could be something that we could tap for this purpose.

**Comment by joncameron** [comment]
Things have improved a lot from the JHOVE days but parsing could still have oddities. We can look at these tools at least and see what they can deliver. This could be something Active Encode could provide; or it could be a separate process like waveform generation. FFprobe will hopefully be able to provide this, and mediainfo as a backup.

**Comment by elynema** [comment]
Most likely collection owner to have content this would apply to would probably be Music.

**Comment by elynema** [comment]
Potentially reach out to Tony Tadey to see if they have an example of a live recording with markers.

**Comment by elynema** [comment]
From Tony: "Yes we are adding marker info to our files.  Both audio and video files will have embedded marker information.
I can share some examples directly, or any concert recording that was recently delivered to MCO should have information.
 
The video may be the most problematic as we use adobe premier as our editing software and it’s marker data is not great on the interoperability side. We do also produce sidecar files with marker data for videos.   We use the sidecar for some automated xml reformatting and that is then currently loaded into MCO for structural metadata
 
Luckily the info in wav header should be much more standardized."

**Comment by elynema** [comment]
MusicBrains has been used in the past, especially better for getting hierarchical tracks for classical music. But if no one is doing significant digitizing of CDs anymore, it may not be relevant.

**Comment by cjcolvar** [comment]
I did a quick test of tools and had the same issues as @masaball with `mediainfo` and `ffprobe` but I did have some success with `jhove` and `exiftool`.  `jhove` worked for the wav file but not the mp4 and vice versa for `exiftool`.  I suspect that it might be possible to get the same information out of FITS (since it can be configured to run both of these tools and more) but I didn't figure that out yet.

### vae5715a.wav
**JHOVE:**
```
   CuePoints: 
    CuePoint: 
     ID: 1
     Position: 0
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 0
    CuePoint: 
     ID: 2
     Position: 6338752
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 6338752
    CuePoint: 
     ID: 3
     Position: 18016504
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 18016504
    CuePoint: 
     ID: 4
     Position: 69657052
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 69657052
    CuePoint: 
     ID: 5
     Position: 91041349
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 91041349
    CuePoint: 
     ID: 6
     Position: 113447870
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 113447870
    CuePoint: 
     ID: 7
     Position: 151913705
     DataChunkID: data
     ChunkStart: 0
     BlockStart: 0
     SampleOffset: 151913705
   ListInfo: 
    Name: Indiana University Jacobs School of Music
    Artist: Thomas Wilkins, Conductor, Yujun Cao, Piano
    Copyright: Indiana University Board of Trustees
    CreationDate: 2025-01-01
    Genre: Philharmonic Orchestra
    Engineer: Henry Thuss, Will Heilbraun, Zach Duigou, Matt Swolsky, Cameron Long
    Keywords: Musical Arts Center
    Subject: 2024-2025
    Software: Wavelab 11
   Labels: 
    Label: 
     CuePointID: 1
     Text: Ambience
    Label: 
     CuePointID: 2
     Text: Announcement
    Label: 
     CuePointID: 3
     Text: Richard Strauss (1864-1949), Till Eulenspiegels lustige Streiche, Op. 28 (1894-95)
    Label: 
     CuePointID: 4
     Text: Alexander Scriabin (1872-1915), Concerto in F-Sharp Minor for Piano and Orchestra, Op. 20 (1896) - Allegro
    Label: 
     CuePointID: 5
     Text: Alexander Scriabin (1872-1915), Concerto in F-Sharp Minor for Piano and Orchestra, Op. 20 (1896) - Andante
    Label: 
     CuePointID: 6
     Text: Alexander Scriabin (1872-1915), Concerto in F-Sharp Minor for Piano and Orchestra, Op. 20 (1896) - Allegro moderato
    Label: 
     CuePointID: 7
     Text: End
```
**Exiftool:**
```
Cue Points                      : (Binary data 172 bytes, use -b option to extract)
Cue Point Label                 : 1 Ambience
Cue Point Note                  : 1 type=4|Id=79117451801500043|RightId=79116531472600039
Title                           : Indiana University Jacobs School of Music
Artist                          : Thomas Wilkins, Conductor, Yujun Cao, Piano
Copyright                       : Indiana University Board of Trustees
Date Created                    : 2025:01:01
Genre                           : Philharmonic Orchestra
Engineer                        : Henry Thuss, Will Heilbraun, Zach Duigou, Matt Swolsky, Cameron Long
Keywords                        : Musical Arts Center
Subject                         : 2024-2025
Software                        : Wavelab 11
```

### vae5714_preservationH264-1080_001.mp4
**JHOVE:**
Nothing useful

**Exiftool:**
```
Tracks Markers Start Time       : 0, 5893, 30877, 55608, 63093, 76167, 84713, 102332, 108407, 128373, 136604, 153078, 164332, 182291, 188396, 212303, 222443
Tracks Markers Duration         : 5893, 24984, 24731, 7485, 13074, 8546, 17619, 6075, 19966, 8231, 16474, 11254, 17959, 6105, 23907, 10140, 22204
Tracks Markers Name             : [ambience], Announcement, Chris Christodoulou (b.1980), Antarctic Oscillation (from Risk of Rain 2, 2020) (arr. Michael Eaton), Announcement, Yasunori Mitsuda (b.1972), Ever Come to an End (from Xenoblade Chronicles 2, 2017) (arr. Sy Anderson), Announcement, David García Díaz (b.1979), The Song of the Sea (from RiME, 2017) (arr. Jamey Guzman), Announcement, Mark Sparling (b.1990), See You at the Top (Flight Mix) (from A Short Hike, 2019) (arr. Youjin Cho), Announcement, Austin Wintory (b.1984), Ichthyosaurus Communis (from Abzû, 2016) (arr. Nehemiah Robertson), Announcement, Lena Raine (b.1984), Confronting Myself (from Celeste, 2018) (arr. Erin C. Blake), Announcement, Yasunori Mitsuda, Shadows of the Lowland (from Xenoblade Chronicles 2, 2017) (arr. Tyree Nesbitt), Announcement, Jonathan Geer (b.1980), Chakalaka (from Cook, Serve, Delicious! 3?!, 2020) (arr. Isaac Smith and Drake Eshleman)
Tracks Markers Type             : Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter, Chapter
```
