### ISSUE TITLE
Add Controlled Digital Lending Values to Avalon Config

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4727]
# Description
Adding a new ability to configure in Avalon's settings file for controlled digital lending, as well as an option value to set the application-wide default for lending periods and value for maximum number of items a patron may borrow at one time.

# Done Looks Like
- [x] A key exists in settings to enable/disableControlled Digital Lending 
- [x] Lending period (if this key does not appear, assign "14 days" as the default)
- [x] Maximum checkouts per user (if this key does not appear, assign "25" as the default)

Something along the lines of:
```
controlled_digital_lending:
  enable: true
  default_lending_period: 14 days
  max_checkouts_per_user: 25
```
