### ISSUE TITLE
Streaming broken on avalon-dev

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5199]
Appears to be due to a bad CORS configuration.

Browser console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://avalon-dev-hls.dlib.indiana.edu/avalon/2eedf9ca-52a8-4ec2-b4cc-0fd832e26a31/outputs/meow-high.mp4/index.m3u8?token=dbf0104a99974aaa90f0fa78bfe3007e08849996. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
```

**Comment by cjcolvar** [comment]
It appears the CORS error might be a red herring.  It appears that the nginx container isn't responding properly and giving a 502 Bad Gateway response.  I tried restarting the service but this didn't seem to help.  avalon-dev is using the same nginx container image and configuration as staging and hasn't changed it recently so I'm guessing that there is something odd about the podman environment which is causing this issue.

**Comment by cjcolvar** [comment]
I restarted avalon-staging and now it is exhibiting the same symptoms as avalon-dev: HLS is returning 502 and nginx access/error logs to stdout/stderr are showing "permission denied".  I tried to change the config to output these logs to files but it doesn't seem to be having any effect.  I'm trying building a new image with an updated base image since the old one is 5 years old.

**Comment by cjcolvar** [comment]
I built a new container image using a newer baseimage.  https://github.com/avalonmediasystem/avalon-docker/pull/73
This didn't appear to solve the problem.  I externalized the nginx template config so I could change the access and error log files to be mounted files instead of stdout/stderr.  Doing these two things allowed streaming to work.  I want to follow up with Brian Wheeler to see why this change was necessary and if it is possible to revert.

**Comment by AbrilJara** [comment]
Hi, i'm having a similar issue with streaming in dev enviroment.

The brave console shows the following error:

`Access to XMLHttpRequest at 'http://my_ip:8880/app/avalon/encode/3501827a-d891-4cdf-924d-fd4acaa7643a/outputs/VULFPECK_20---_20Running_20Away_20_28feat_20Joey_20Dosik_2C_20David_20T_20Walker_20_26_20James_20Gadson_29-medium.mp4/index.m3u8?token=1d762166ffeed4253c9889c6113aee70739bf183' from origin 'http://my_ip:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

And then a forbiden 403 error:

`GET http://my_ip:8880/app/avalon/encode/3501827a-d891-4cdf-924d-fd4acaa7643a/outputs/VULFPECK_20---_20Running_20Away_20_28feat_20Joey_20Dosik_2C_20David_20T_20Walker_20_26_20James_20Gadson_29-medium.mp4/index.m3u8?token=1d762166ffeed4253c9889c6113aee70739bf183 net::ERR_FAILED 403 (Forbidden)
t.loa`

My docker-compose file:

```yaml
version: '3.4'

volumes:
  database:
  fedora:
  solr:
  npms:
  data:

networks:
  internal:
  external:

services:
  db: &db-avalon
    image: postgres:14-alpine
    volumes:
      - database:/data
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_DB=avalon
      - POSTGRES_PASSWORD=password
    networks:
      internal:
  db-test:
    <<: *db-avalon
    volumes: []

  fedora: &fedora
    image: avalonmediasystem/fedora:4.7.5
    depends_on:
      - db
    volumes:
      - fedora:/data
    environment:
      - JAVA_OPTIONS=-Dfcrepo.modeshape.configuration=classpath:/config/file-simple/repository.json -Dfcrepo.home=/data
    networks:
      internal:
  fedora-test:
    <<: *fedora
    volumes: []

  solr: &solr
    image: solr:8-slim
    volumes:
      - ./solr/conf:/opt/solr/avalon_conf
      - solr:/var/solr
    command:
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
    networks:
      internal:
  solr-test:
    <<: *solr
    volumes:
      - ./solr/conf:/opt/solr/avalon_conf

  hls:
    image: avalonmediasystem/nginx:minio
    environment:
      - AVALON_DOMAIN=http://avalon:3000
      - AVALON_STREAMING_BUCKET_URL=http://minio:9000/derivatives/
    ports:
      - '8880:80'
    networks:
      internal:
      external:

  redis: &redis
    image: redis:alpine
    networks:
      internal:
  redis-test:
    <<: *redis

  avalon: &avalon
    image: avalonmediasystem/avalon:7.4.0-dev
    build:
      context: .
      target: dev
    command: bash -c "/docker_init.sh && bundle exec rails server -b 0.0.0.0"
    depends_on:
      - db
      - fedora
      - solr
      - redis
      - hls
      - minio
    environment:
      - APP_NAME=avalon
      - BUNDLE_FLAGS=--with development postgres --without production test
      - ENCODE_WORK_DIR=/home/app/avalon/encode
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgres://postgres:password@db/avalon
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora/rest
      - RAILS_ENV=development
      - RAILS_ADDITIONAL_HOSTS=avalon
      - SETTINGS__REDIS__HOST=redis
      - SETTINGS__REDIS__PORT=6379
      - SECRET_KEY_BASE=abcd
      - SOLR_URL=http://solr:8983/solr/avalon
      - AWS_REGION=us-east-1
      - SETTINGS__ACTIVE_STORAGE__BUCKET=supplementalfiles
      - SETTINGS__ACTIVE_STORAGE__SERVICE=generic_s3
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__MINIO__ENDPOINT=http://minio:9000
      - SETTINGS__MINIO__PUBLIC_HOST=http://my_ip:9000
      - SETTINGS__MINIO__ACCESS=minio
      - SETTINGS__MINIO__SECRET=minio123
      - SETTINGS__ENCODING__MASTERFILE_BUCKET=masterfiles
      - SETTINGS__ENCODING__DERIVATIVE_BUCKET=derivatives
      - SETTINGS__DROPBOX__PATH=/home/app/avalon/dropbox
      - SETTINGS__DROPBOX__UPLOAD_URI=sftp://my_ip
      - SETTINGS__MASTER_FILE_MANAGEMENT__STRATEGY=none
      - SETTINGS__STREAMING__CONTENT_PATH=http://my_ip:9000/minio/derivatives
      - SETTINGS__STREAMING__STREAM_DEFAULT_QUALITY=medium
      - SETTINGS__STREAMING__HTTP_BASE=http://my_ip:8880/avlon
      - SETTINGS__STREAMING__SERVER=nginx
      - SETTINGS__STREAMING__STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
    volumes:
      - .:/home/app/avalon
      - npms:/home/app/avalon/node_modules
    ports:
      - '3000:3000'
    networks:
      internal:
      external:
    stdin_open: true
    tty: true

  test:
    <<: *avalon
    command: >
      bash -c "/docker_init.sh && tail -f /dev/null"
    depends_on:
      - db-test
      - fedora-test
      - solr-test
      - redis-test
    environment:
      - DATABASE_URL=postgresql://postgres:password@db-test/avalon
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - SETTINGS__REDIS__HOST=redis-test
      - SETTINGS__REDIS__PORT=6379
      - FEDORA_URL=http://fedora-test:8080/fedora/rest
      - SOLR_URL=http://solr-test:8983/solr/avalon
      - RAILS_ENV=test
      - BUNDLE_FLAGS=--with aws test postgres --without production
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
    ports: []

  worker:
    <<: *avalon
    command: dumb-init -- bash -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    ports: []

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    command: minio server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - data:/data
    ports:
      - 9000:9000
    networks:
      internal:
      external:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb -p myminio/fcrepo myminio/masterfiles myminio/derivatives myminio/supplementalfiles myminio/preserves;
      /usr/bin/mc policy set download myminio/derivatives;
      /usr/bin/mc policy set download myminio/supplementalfiles;
      exit 0;
      "
    networks:
      internal:

  cypress:
    network_mode: host
    image: cypress/included:3.8.2
    depends_on:
      - avalon
    entrypoint: cypress run -C spec/cypress/cypress.json
    working_dir: /e2e
    volumes:
      - ./:/e2e
      - npms:/e2e/node_modules
```

There some enviromental values that I don't really understand how to configure them like SETTINGS__STREAMING__CONTENT_PATH. Is there any documentation about env vars and why they mean? because I couldn't find any.
