### ISSUE TITLE
Fix IIIF Manifest Errors - Media Objects

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#5798]
## Description

Follow-up ticket for #5571. The errors listed in the ticket for inaccessible items and structures were given for both playlist and media object manifests. For the playlist manifests, see #5802.

In the media object context, sections still processing and sections where processing failed are presented as inaccessible items in the IIIF manifest.

## Done Looks Like
For media object manifests:
- [ ] the root `Range` node in the `structures` property has a `label` property with a language map instead of `null`
**For inaccessible items;**
- [ ] `body` in the `placeholderCanvas` has a value for the `id` property instead of `null`
- [ ] `placeholderCanvas` has `height` and `width` properties
- [ ] `AnnotationPage` in the `Canvas` `must` have an `items` list with at least one `Annotation` (https://www.w3.org/TR/annotation-model/#annotation-page)
- [ ] `Canvas` has `height` and `width` properties

**Comment by joncameron** [comment]
Manifest generation is separate for media objects and playlists; this ticket can be broken in two: one for media objects, and one for playlists. The same set of issues need to be corrected in both places.

**Comment by Dananji** [comment]
Three more issues were found in audio manifests:

#### Error 1:
Message: 0 is less than or equal to the minimum of 0
```
Detail:
Path: /items[0]/height/[0 is less than or equal to the minimum of 0]
Description: 0
```
**Fix suggestion: _set `height` to a value not zero for audio master file_**

### Error 2:
Message: 0 is less than or equal to the minimum of 0
```
Detail:
Path: /items[0]/width/[0 is less than or equal to the minimum of 0]
Description: 0
```
**Fix suggestion: _set `width` to a value not zero for audio master file_**

### Error 3:
Message: '/assets/audio_icon-7782bcf9fd5d81f1e3e3f260ed569c24dea47d0a2a5bd0a4629328c76e8886c6.png' does not match '^http.*$'
```
    Detail: Id must be present and must be a URI
    Path: /thumbnail[0]/id/['/assets/audio_icon-7782bcf9fd5d81f1e3e3f260ed569c24dea47d0a2a5bd0a4629328c76e8886c6.png' does not match '^http.*$']
    Description:

    "/assets/audio_icon-7782bcf9fd5d81f1e3e3f260ed569c24dea47d0a2a5bd0a4629328c76e8886c6.png"
```
**Fix suggestion: _change thumbnail `id` to a URL_**
